language: node_js
node_js:
  - "6"

notifications:
  slack:
    rooms:
      - indaym:q8No60ybN9tfQyWop7cW0zWY#back-end-ci

branches:
  only:
    - master
    - develop
    - /^feature\/*/
    - /^hotfix/\/*/

install:
  - npm install

script:
  - npm test
